CREATE DATABASE IF NOT EXISTS desafio2;

USE desafio2;

CREATE TABLE CATEGORIA(
	idCategoria NUMERIC(2) ,
    nomeCategoria VARCHAR(50) NOT NULL,	
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (idCategoria)
) ENGINE = InnoDB ;

CREATE TABLE MODELO(
	idModelo NUMERIC(6) NOT NULL,
    marca VARCHAR(30) NOT NULL,	
    nomeModelo VARCHAR(50) NOT NULL,	
    CONSTRAINT MODELO_PK PRIMARY KEY (idModelo)
) ENGINE = InnoDB;

CREATE TABLE TIPOINFRACAO(
	idTipoInfracao TINYINT NOT NULL AUTO_INCREMENT,
    valor DECIMAL(6,2) NOT NULL,	
    nome VARCHAR(120) NOT NULL,	
    CONSTRAINT TIPOINFRACAO_PK PRIMARY KEY (idTipoInfracao)
) ENGINE = InnoDB AUTO_INCREMENT=1;

CREATE TABLE PROPRIETARIO(
	cpf NUMERIC(11) NOT NULL,
    nomeCompleto VARCHAR(100) NOT NULL,
    cidade VARCHAR(50) NOT NULL, 
    bairro VARCHAR(50) NOT NULL, 
    estado VARCHAR(50) NOT NULL, 
    logradouro VARCHAR(50) NOT NULL,
    dataNascimento DATE NOT NULL,
    sexo ENUM('M', 'F') NOT NULL,
    CONSTRAINT PROPRIETARIO_PK PRIMARY KEY (cpf)
) ENGINE = InnoDB;

CREATE TABLE telefone(
	numero NUMERIC(12) NOT NULL,
    cpf NUMERIC(11) NOT NULL, 
    CONSTRAINT TELEFONE_PROPRIETARIO_FK FOREIGN KEY (cpf) REFERENCES PROPRIETARIO (cpf)
		ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE VEICULO(
	placa VARCHAR(7) NOT NULL,
    corPredominante VARCHAR(30) NOT NULL,
    chassi VARCHAR(17) NOT NULL, 
    anoFabricacao NUMERIC(4) NOT NULL, 
    idModelo NUMERIC(6) NOT NULL, 
    idCategoria NUMERIC(2) NOT NULL,
    CONSTRAINT VEICULO_PK PRIMARY KEY (placa),
    CONSTRAINT VEICULO_MODELO_FK FOREIGN KEY (idModelo) REFERENCES MODELO (idModelo),
    CONSTRAINT VEICULO_CATEGORIA_FK FOREIGN KEY (idCategoria) REFERENCES CATEGORIA (idCategoria)
) ENGINE = InnoDB;

CREATE TABLE possui(
	cpf NUMERIC(11) NOT NULL,
    placa VARCHAR(7) NOT NULL,
    CONSTRAINT possui_PROPRIETARIO_FK FOREIGN KEY (cpf) REFERENCES PROPRIETARIO (cpf),
    CONSTRAINT possui_VEICULO_FK FOREIGN KEY (placa) REFERENCES VEICULO (placa)
) ENGINE = InnoDB;

CREATE TABLE LOCALIDADE(
	latitude VARCHAR(10) NOT NULL,
    longitude VARCHAR(10) NOT NULL,
    velocidadePermitida NUMERIC(3) NOT NULL,
    CONSTRAINT LOCALIDADE_PK PRIMARY KEY (latitude, longitude)
) ENGINE = InnoDB;

CREATE TABLE AGENTE(
	matricula NUMERIC(11) NOT NULL,
    nomeCompleto VARCHAR(50) NOT NULL,
    dataContratacao DATE NOT NULL, 
    CONSTRAINT AGENTE_PK PRIMARY KEY (matricula)
) ENGINE = InnoDB;

CREATE TABLE INFRACAO(
	idInfracao TINYINT NOT NULL AUTO_INCREMENT,
    dataHora DATETIME NOT NULL,
    velocidadeAferida NUMERIC(3), 
    idTipoInfracao TINYINT NOT NULL,
    matricula NUMERIC(11) NOT NULL,
    latitude VARCHAR(10) NOT NULL,
    longitude VARCHAR(10) NOT NULL,
    CONSTRAINT AGENTE_PK PRIMARY KEY (idInfracao),
    CONSTRAINT INFRACAO_TIPOINFRACAO_FK FOREIGN KEY (idTipoInfracao) REFERENCES TIPOINFRACAO (idTipoInfracao),
    CONSTRAINT INFRACAO_AGENTE_FK FOREIGN KEY (matricula) REFERENCES AGENTE (matricula),
    CONSTRAINT INFRACAO_LOCALIDADE_FK FOREIGN KEY (latitude, longitude) REFERENCES LOCALIDADE (latitude, longitude)
) ENGINE = InnoDB AUTO_INCREMENT=1;

CREATE TABLE comete(
	placa VARCHAR(7) NOT NULL,
    idInfracao TINYINT NOT NULL,
    CONSTRAINT comete_VEICULO_FK FOREIGN KEY (placa) REFERENCES VEICULO (placa)
		ON DELETE RESTRICT,
    CONSTRAINT comete_INFRACAO_FK FOREIGN KEY (idInfracao) REFERENCES INFRACAO (idInfracao)
		ON DELETE RESTRICT
) ENGINE = InnoDB;